ANCH_DICT = {
    "top": [
        "top left",
        "top right",
        "top center",
        "center top",
        "right top",
        "left top",
        "top-left",
        "top-right",
        "top-center",
        "center-top",
        "right-top",
        "left-top",
    ],
    "bottom": [
        "bottom left",
        "bottom right",
        "bottom center",
        "center bottom",
        "right bottom",
        "left bottom",
        "bottom-left",
        "bottom-right",
        "bottom-center",
        "center-bottom",
        "right-bottom",
        "left-bottom",
    ],
    "left": [
        "left top",
        "left bottom",
        "left center",
        "center left",
        "bottom left",
        "top left",
        "left-top",
        "left-bottom",
        "left-center",
        "center-left",
        "bottom-left",
        "top-left",
    ],
    "right": [
        "right top",
        "right bottom",
        "right center",
        "center right",
        "bottom right",
        "top right",
        "right-top",
        "right-bottom",
        "right-center",
        "center-right",
        "bottom-right",
        "top-right",
    ],
}
