from pathlib import Path
from datetime import datetime

from loguru import logger
from utils.jsonc import Jsonc
import re


class StyleHandler:
    """Convert JSONC (with comments) → SCSS and auto-save"""

    def __init__(self, json_style: dict, file_path: Path) -> None:
        """
        :param json_style: dict with style from JSONC
        :param file_path: path to css file
        """
        self.json_style = json_style
        self.file_path = file_path

        scss_path = self.file_path.with_suffix(".scss")

    def extract_comments(self) -> list[str]:
        if not self.file_path.exists():
            return []
        content = self.file_path.read_text(encoding="utf-8")
        return re.findall(r"^\s*//.*$", content, flags=re.MULTILINE)

    def to_scss(self) -> str:
        lines = []

        comments = self.extract_comments()
        if comments:
            lines.extend(comments)
            lines.append("")

        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines.append(f"// generated by moonlight at {now}")
        lines.append("")

        imports = self.json_style.get("import", [])
        for imp in imports:
            lines.append(f'@use "{imp}";')
        if imports:
            lines.append("")

        for selector, props in self.json_style.items():
            if selector == "import":
                continue
            lines.append(f"{selector} {{")
            for prop, value in props.items():
                lines.append(f"  {prop}: {value};")
            lines.append("}")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def save_scss(self, output_path: Path | None = None) -> None:
        output_path = output_path or self.file_path.with_suffix(".scss")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        scss_code = self.to_scss()
        output_path.write_text(scss_code, encoding="utf-8")

        logger.debug(f"[StyleHandler] Saved SCSS → {output_path}")
